### ISSUE TITLE
HTTPBadRequest 400 UnauthorizedRegistration

### ISSUE THREAD

**Issue by nononoy** [zaru/webpush#11]
Some days ago i noticed all my pushes have been rejected by server. But a week ago all was OK. 
```
Webpush.payload_send(message:  JSON.generate(message),
                             endpoint: sub.gcm_url,
                             p256dh:   sub.key_p,
                             auth:     sub.key_a,
                             api_key:  GOOGLE_API_KEY)

returns me #<Net::HTTPBadRequest 400 UnauthorizedRegistration readbody=true>
```
May be google have made any changes in GCM?

**Comment by rossta** [comment]
Thanks for sharing your issue. My first guess is about the time-to-live expiration on push registrations. The [default TTL](https://github.com/zaru/webpush/blob/336874a55ee0dd7273db01767929cd7588d20276/lib/webpush/request.rb#L70) is 4 weeks. Is it possible this is an expired registration? Could you try getting a new set of credentials and see if the requests work again?

**Comment by nononoy** [comment]
I have used some new non-expired credentials. And I am really embarrassed by 400, instead of 401 error status.

**Comment by rossta** [comment]
Ok, I also was mistaken - the TTL is for the notification, not the subscription. Can try to troubleshoot later.

**Comment by zaru** [comment]
@nononoy 
thanks for report. 
Maybe I do not think have changed the specifications of the GCM.

The combination of gcm_sender_id and API_KEY, correct?
Or endpoint might have been disabled.

**Comment by nononoy** [comment]
Thanks for your support. I found the [solution](https://github.com/GoogleChrome/web-push-encryption/issues/29) in nodeJS repo. I realized that problem were in the Google Cloud Platform activation. After I changed my billing plan - pushes started to work. Thanks
