### ISSUE TITLE
VAPID support

### ISSUE THREAD

**Issue by mohamedhafez** [zaru/webpush#13]
Chrome 52 and Firefox 48, both currently in beta and due to be released late July / early August, are both implementing [VAPID](https://blog.mozilla.org/services/2016/04/04/using-vapid-with-webpush/), are there any plans to update this library to support that?

**Comment by zaru** [comment]
Yes. I'll support the VAPID.
Until chrome52 is released if possible.

**Comment by mohamedhafez** [comment]
Just a little ping, Chrome now supports VAPID, and Firefox will as well by Aug 6:)

**Comment by rossta** [comment]
@mohamedhafez VAPID support has now landed in version `0.3.0`

**Comment by mohamedhafez** [comment]
Awesome just saw it, thanks!!
