### ISSUE TITLE
Raising errors when sending request fails, detecting when subscription no longer valid

### ISSUE THREAD

**Issue by mohamedhafez** [zaru/webpush#17]
Right now, when a request fails, nothing happens and the only way the user would know is by inspecting the response object returned from `Webpush::Request#perform`. The user could parse the response to figure out why the failure happened, but I think this should be taken care of by the gem.

I've got a patch to detect when the failure is because the subscription/endpoint is no longer valid and then raise a `InvalidSubscription` error, and then if the request fails for any other reason a `ResponseError` error is raised, and the only way the method would return without raising an exception is if the request went through. If that sounds good to everyone I'll issue a pull request

**Comment by rossta** [comment]
Yes, I like this idea. There's probably a set of errors we can wrap--timeout, unauthorized API key, to name a few--which would also be a nice way to abstract differences across push server providers. Adding one for an invalid subscription sounds like a good start to me.

**Comment by zaru** [comment]
released https://github.com/zaru/webpush/pull/18
