### ISSUE TITLE
Extract logic to ece gem?

### ISSUE THREAD

**Issue by rossta** [zaru/webpush#2]
I was looking into writing a webpush ruby implementation and came across your gem. Nice work!

In my research I can across another gem, [ece](https://github.com/randomlogin/ece), that abstracts the [HTTP encrypted content protocol](https://tools.ietf.org/html/draft-thomson-http-encryption-02#page-9). 

Would you be interested in a PR to introduce ece as a dependency to extract the encryption logic in your gem?

**Comment by zaru** [comment]
@rossta thank you.
ece is looks good.  I welcome pull request.
