### ISSUE TITLE
how long is a "user" token+auth valid?

### ISSUE THREAD

**Issue by rlech** [zaru/webpush#33]
it looks like the google docs say just trust them for 24h? so if a user got a token he only gets web push notifications for 24h and have to revisit my page to get new tokens?

**Comment by zaru** [comment]
@rlech 
JWT is valid for up to 24 hours.
I think that Endpoint has no expiration date.

ref: https://developers.google.com/web/updates/2016/07/web-push-interop-wins#sending_a_push_message

**Comment by collimarco** [comment]
Yes, **JWT is valid for at most 24 hours**: this gem manages that properly.

The **endpoint can expire**:
- it returns 410 Gone
- it can also have an expiration time: https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/expirationTime 

Endpoint expiration management is out of scope for this gem, so this issue should be closed. @zaru
