### ISSUE TITLE
Where should the post endpoint be placed

### ISSUE THREAD

**Issue by jorgecuevas92** [zaru/webpush#35]
I've been unable to make the endpoint work the way it is stated on the read me. It says:

"Imagine a Ruby app endpoint that responds to the request by triggering notification through the webpush gem."

And the code itself says it should go on app.rb but so far I've had errors on server start up by placing the code inside application.rb

I also tried creating a route and executing the code inside a controller but I get the following error:

> NoMethodError in DemoController#push
> undefined method `gsub' for nil:NilClass

I'm using rails 4.2.6

What am I missing to make this work?

**Comment by rossta** [comment]
The code in the README could be part of an app that's built with the Sinatra framework. Check out the [Sinatra](http://www.sinatrarb.com/) documentation for more info to help understand how the example would fit into an application.

You'll have to share the relevant code and the whole backtrace for us to help with the error you're seeing.
