### ISSUE TITLE
HTTPBadRequest 400 UnauthorizedRegistration on Chrome only

### ISSUE THREAD

**Issue by victorfonsec4** [zaru/webpush#40]
I'm getting this 400 error when sending notifications to Chrome, but on firefox everything works as expected.

Is there some additional parameters that need to be send on chrome? My request is sent using:

```
    Webpush.payload_send(
      message: message,
      endpoint: endpoint_url,
      p256dh: p256dh,
      auth: auth,
      vapid: {
        public_key: vapid_keypair['public_key'],
        private_key: vapid_keypair['private_key']
      }
    )
```

**Comment by zaru** [comment]
@victorfonsec4 Thanks for report.
Sorry for the late reply.

Is this issue helpful for you?
https://github.com/zaru/webpush/issues/11#issuecomment-221869405

Or could you show me the settings of `manifest.json` ?

**Comment by zaru** [comment]
It's my sample app `manifest.json` .

```
{
  "name": "SampleApp",
  "short_name": "SampleApp",
  "start_url": "/",
  "display": "standalone"
}
```

**Comment by victorfonsec4** [comment]
Sorry I don't have access to the code anymore, should I close this?

**Comment by zaru** [comment]
OK Feel free to ask me if you have any questions
