### ISSUE TITLE
webpush fails with new jwt and Chrome.

### ISSUE THREAD

**Issue by GrandVizierOlaf** [zaru/webpush#42]
The jwt gem was just updated to version 2.0.0 and that version causes webpush to no longer send push messages to Chrome.

I had to downgrade jwt to version 1.5.6 for Chrome to start working again so it would be nice to include that in the Gemfile of webpush for now. I can create a PR if you agree.

**Comment by KeithP** [comment]
We hit this issue too

**Comment by zaru** [comment]
@GrandVizierOlaf Thenks for the report.
It would be very helpful if you create PR.
