### ISSUE TITLE
web push notifications does not show up if there is already unopened notification

### ISSUE THREAD

**Issue by calvinsug** [zaru/webpush#44]
I have followed the instructions and i have success implemented it, (i got the push notification). But, there is a problem i faced right now when i have received my push notification.

If i didn't open/closed my previous notification, i couldn't get any new push notification until i closed my previous notification, i have tried to shorten the ttl (expiration time), but it won't closed by itself after the expiration time is expired (it didn't happen anything)

`Webpush.payload_send(
      message: params[:message],
      endpoint: admin.subscription[:endpoint],
      p256dh: admin.subscription[:keys][:p256dh],
      auth: admin.subscription[:keys][:auth],
      ttl: 10, //10 seconds based on documentation
      vapid: {
          subject: 'mailto:calvin@thechordgenius.com',
          public_key: ENV['VAPID_PUBLIC_KEY'],
          private_key: ENV['VAPID_PRIVATE_KEY']
      }
  )`

**Comment by xavijs** [comment]
Did you try it with different data? I've got a similar issue and was because I was reproducing exactly the same notification.

**Comment by calvinsug** [comment]
i have solved it anyway,

the problem is in my tag when we want to push notification
` event.waitUntil(
        self.registration.showNotification(title, {
            body: body,
            icon: icon,
            tag: tag,
            data: data
        })
    )`

we have to push different tag to differentiate every push notifications we want to show

**Comment by collimarco** [comment]
This is the expected behavior for the `tag` option of the Push API. 

This issue should be closed. @zaru
