### ISSUE TITLE
Please update this library to use RFC 8188 Content encoding spec

### ISSUE THREAD

**Issue by jrconlin** [zaru/webpush#60]
First off, thanks for this library. 

[RFC 8188](https://datatracker.ietf.org/doc/rfc8188/?include_text=1) has been out for a while, and services will soon start deprecating the "aesgcm" encoding type. The differences aren't that much (the salt is included in the data prefix, and the nonce phrases changed to reflect the new content encoding schema).

Thanks!

**Comment by collimarco** [comment]
@jrconlin Can you take a look to the library and suggest what parts of the code should be changed? Can you give some more specific hints about what must be changed?

I am not an expert in cryptography and RFC 8188 is not very simple... maybe @zaru or @rossta that wrote the payload encryption have a better understanding. When you have time, can you take a look at this?

**Comment by jrconlin** [comment]
Heh, I'm not super familiar with ruby, so I guess we'll have to split the difference.

The main changes between aesgcm and aes128gcm have to do with:
* The Key Info prefix changed from `Content-Encoding: aesgcm\0P-256\0` to `Content-Encoding: aes128gcm\0`
* The Nonce Info prefix changed from `Content-Encoding: nonce\0P-256\0' to `Content-Encoding: nonce\0`
* The IKM changed from `Content-Encoding: auth\0` to `WebPush: info\0`
* Pad size changed from `2` to `1`
* `salt` and `dh` are no longer passed via discrete header values, but instead added as a body header:

| `salt` (16 octets) | `rs` (4 octets) | `public key` (65 octets) | `encrypted body` ...

* The Initial Key Material Info changes to 
| `WebPush: info\0` | `Receiver Public Key` | `Sender Public Key` 
(Note: keys are NOT prefixed with their lengths.)

* The IKM is now a HKDF/SHA-256 of the IKM Info, instead of `Content-Encoding: auth\0`

FWIW, I usually find it's easiest to try creating the encrypted block using one language, and then decrypt using a different one, like the [python](https://github.com/web-push-libs/pywebpush) or [rust](https://github.com/mozilla/rust-ece) libraries.  The unit tests (particularly [the rust one](https://github.com/mozilla/rust-ece/blob/master/src/lib.rs#L96) have hex encoded values that you can use as test data. 

Sorry about sucking at ruby. If I get a bit more free time, I'll see if I can do anything.

**Comment by collimarco** [comment]
@jrconlin 

1. Is it enough to collect the `endpoint`, `auth`, `p256dh` from the client as we did in the past? Or now there are new fields to collect?
2. Does this change affects the delivery of push messages _without_ payload (only endpoint + VAPID)?

**Comment by jrconlin** [comment]
@collimarco 
1. Yep, you'll still have to collect the subscription info (endpoint, auth & p256dh). The changes are more about how the content you're sending is generated.
2. Messages without payload don't have to do ECE encryption (the bit that's changed), so no worries there. Things should continue to work fine.

**Comment by mplatov** [comment]
I've tried implementing changes @jrconlin mentioned in the encryption code, by adding a parameter to the Encryption.encode function to change the payload it generates. It defaults to the old aesgcm variant for compatibility reasons, but it will produce aes128gcm encrypted payload if called with aes128gcm value. More changes are needed for the gem though: removing Encryption and Crypto-Key headers (for aes128gcm payload those are in the payload itself, so they shouldn't be in the headers) and possibly, a gem option to control which type of the payload it should generate.

**Comment by mohamedhafez** [comment]
Awesome @mplatov! Why do we need to revert to the old aesgcm varient for compatibility reasons though, do some push services not accept aes128gcm yet? If so, rather than make the user turn this option on and off, I think we should make the library automatically use aes128gcm for endpoints that support it, and fall back automatically to the old aesgcm for endpoints that we know don't support it yet. (i.e. it would be nice if the gem kept track of which encoding should be used in which instance instead of make each user of the gem figure it out)

**Comment by mplatov** [comment]
@mohamedhafez. I'm not aware of any push services besides Mozilla's and Google's (both support aes128gcm). Are there any?

**Comment by collimarco** [comment]
@mplatov Yes, there is also _Windows Push Notification Services_ for Edge. We keep a list of all push service domains here: https://github.com/pushpad/known-push-services/blob/master/whitelist

**Comment by mohamedhafez** [comment]
@mplatov, Edge also supports aes128gcm according to the [Microsoft Edge team's response to this issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15893079/), so I'd say go ahead and make all the other necessary changes you mentioned, with no need for a fallback to the soon-to-be-deprecated aesgcm

**Comment by mohamedhafez** [comment]
@zaru this issue can be closed now as of the 1.0.0 release, @jrconlin thanks for bringing this to our attention!
