### ISSUE TITLE
Rescue for exeptions in loop when sending out push 

### ISSUE THREAD

**Issue by Rubioli** [zaru/webpush#64]
First of all, great gem 🥇 

In my application, I ran a loop over subscribers in my controller and send a notification to them.

```
subscribers.each do |sub|
  begin
    Webpush.payload_send(
      endpoint: sub.endpoint,
      message: JSON.generate(data),
      p256dh: sub.p256dh_key,
      auth: sub.auth_key,
      vapid: {
        subject: 'https://my-site.com',
        public_key: 'vapid_public',
        private_key: 'vapid_private'
      }
    )
  rescue Webpush::Unauthorized
    sub.update(status: 0)
    next
  rescue OpenSSL::PKey::EC::Point::Error
    sub.update(status: 0)
    next
  end
end
```

I'm now suing `rescue` for `Webpush::Unauthorized` & `OpenSSL::PKey::EC::Point::Error` for updating sunscriber's `status`.

_PS: I got `Webpush::Unauthorized` when I inserted wrong `endpoint` and `OpenSSL::PKey::EC::Point::Error` when  `p256dh` was wrong_

I'm not sure if there are other exceptions/`rescue` I can add or a better way to add `rescue` so the loop doesn't stop and can continue in case any user data is not `correct`.

Any help is appreciated and thanks in advance! 🍻

**Comment by collimarco** [comment]
This is a question and not a bug...

In any case you can see all the exceptions here (the names are self explanatory):
https://github.com/zaru/webpush/blob/master/lib/webpush/errors.rb
https://github.com/zaru/webpush/blob/master/lib/webpush/request.rb#L29

**Comment by Rubioli** [comment]
Thanks a lot @collimarco, for the links

No it's not a bug, this gem is a real solid gem 💯
