### ISSUE TITLE
Web push failed? only for chrome after succeed once

### ISSUE THREAD

**Issue by kimyu92** [zaru/webpush#68]
I have created a [simple web push demo](https://github.com/kimyu92/rails-webpush-demo). So far, I can send notification to firefox without problem. 

However, I can only do it once for chrome for some unknown reasons. 

The way I have setup: 
- by generating VAPID public and private keys to send notification to chrome (v73, mac os)
- adding `api_key` to webpush from backend
- adding project number (obtained from google console) which is also known as `gcm_sender_id` to `manifest.json`

Here is the dashboard from google console, in case it helps
<img width="1131" alt="google_console_fcm" src="https://user-images.githubusercontent.com/2663509/54732209-84e42a80-4b60-11e9-8252-d4129f516a56.png">

Also, there was an [issue](https://github.com/zaru/webpush/issues/42) mentioned about the gem would not work with `jwt` above v2? It would be great if anyone can clarify about this.

**Comment by zaru** [comment]
@kimyu92 Do you get an error when sending?

**Comment by kimyu92** [comment]
@zaru There was no error when sending/receiving the message.

I have tweaked the rest of the code, to clarify things up, the latest webpush is actually working fine with JWT 2.

In order for notification to show up on chrome, I have to avoid passing `tag` to the notification options.
I suspect chrome doesn't like the fact of using same tag?
```js
self.addEventListener('push', function(event) {
  // ... within push callback
  event.waitUntil(
    self.registration.showNotification(title, {
      body: body,
      icon: icon,
      // tag: tag
    })
  );
```

Also, according to [Can I use](https://caniuse.com/#search=push%20api) site, Microsoft Edge seems to support push api since v17.  Does the gem support Microsoft Edge as well?
