### ISSUE TITLE
Bump to version 1.0.0 after PR #84 gets merged

### ISSUE THREAD

**Issue by mohamedhafez** [zaru/webpush#83]
Hey @zaru, considering that this is now a stable library thats fit for production use at this point, I think it would be a good idea to bump the version to 1.0.0 after https://github.com/zaru/webpush/pull/84 gets merged to communicate that. If more people think its a usable library instead of still in development and not ready for production use, we're likely to get more users, some of whom will also help contribute to the project

**Comment by zaru** [comment]
@mohamedhafez Thanks for your advice and PR.
I merged and bump the version to 1.0.0.
