### ISSUE TITLE
Got an error: 403 Forbidden, exp more than 24 hours 

### ISSUE THREAD

**Issue by matrixue** [zaru/webpush#87]
My webpush doesn't work on AWS server and got this error: "403 forbidden, exp claim must not more than 24 hours from the time of the request". But it works fine on local console. 
My code:
```
Webpush.payload_send(
  endpoint: s.end_point,
  message: {
    title: message_body,
    url: url.to_s
  }.to_json,
  p256dh: s.p256dh,
  auth: s.auth,
  ttl: 24 * 60 * 60,
  vapid: {
    subject: "mailto:tech@ace-up.com",
    public_key: Rails.application.secrets.WEB_PUSH_PUBLIC_KEY,
    private_key: Rails.application.secrets.WEB_PUSH_PRIVATE_KEY
  }
)
```
Is it because I miss something in the `payload_send` method for authentication or should I add `exp` at somewhere

**Comment by wbotelhos** [comment]
I had to use 21 hours, because `Time.now` returns 3 more hours as UTC and adding up to 24 hours, giving a total of 27 hours and so the error. Thanks for your answer @matrixue , I couldn't see this options on documentation.
