### ISSUE TITLE
Intermittent Webpush::Unauthorized errors from FCM

### ISSUE THREAD

**Issue by mohamedhafez** [zaru/webpush#89]
Only in the last month or so, I've intermittently been getting Webpush::Unauthorized errors, with message `invalid push subscription endpoint` for Chrome users. It only affects 2-3 users, keeps up for about a day for every message sent to those 2-3 users, and then without me changing anything messages to those users start going through without issue. But then a different 2-3 users start having the problem for about a day.

Anybody else experiencing this? Any idea what could be going on?

**Comment by collimarco** [comment]
I have no idea... You can try to post this issue on the Chromium bug tracker. If you can give them the endpoint they should be able to investigate the specific issue.

**Comment by niklat22** [comment]
It is possible to refresh endpoint, p256dh, auth just like FCM provides refresh token?

**Comment by crow1796** [comment]
Has anyone got any solution for this?

**Comment by SampsonCrowley** [comment]
@mohamedhafez have you been renewing subscriptions? push notification subscriptions periodically expire

**Comment by collimarco** [comment]
@mohamedhafez Do you still see that issue? I haven't seen any problems and this can probably be closed

**Comment by mohamedhafez** [comment]
Looking at my logs out of all the webpushes I've sent, I've only gotten this like 6 times over the last 6 months, just randomly. It's probably some weird one-off server error happening on FCM's part I'm guessing, and definitely low frequency enough to be ignorable now, so closing the issue
